groups:
  - name: events
    rules:
      - record: kubemq:messages:count:events:send:sum
        expr: sum(kubemq_messages_count{type="events",side="send"}) OR on() vector(0)
      - record: kubemq:messages:count:events:receive:sum
        expr: sum(kubemq_messages_count{type="events",side="receive"}) OR on() vector(0)
      - record: kubemq:messages:count:events:sum
        expr: kubemq:messages:count:events:send:sum+kubemq:messages:count:events:receive:sum
      - record: kubemq:messages:volume:events:send:sum
        expr: sum(kubemq_messages_volume{type="events",side="send"}) OR on() vector(0)
      - record: kubemq:messages:volume:events:receive:sum
        expr: sum(kubemq_messages_volume{type="events",side="receive"}) OR on() vector(0)
      - record: kubemq:messages:volume:events:sum
        expr: kubemq:messages:volume:events:send:sum+kubemq:messages:volume:events:receive:sum
      - record: kubemq:messages:errors:events:sum
        expr: sum(kubemq_errors_count{type="events"}) OR on() vector(0)
  - name: events_store
    rules:
      - record: kubemq:messages:count:events_store:send:sum
        expr: sum(kubemq_messages_count{type="events_store",side="send"}) OR on() vector(0)
      - record: kubemq:messages:count:events_store:receive:sum
        expr: sum(kubemq_messages_count{type="events_store",side="receive"}) OR on() vector(0)
      - record: kubemq:messages:count:events_store:sum
        expr: kubemq:messages:count:events_store:send:sum+kubemq:messages:count:events_store:receive:sum
      - record: kubemq:messages:volume:events_store:send:sum
        expr: sum(kubemq_messages_volume{type="events_store",side="send"}) OR on() vector(0)
      - record: kubemq:messages:volume:events_store:receive:sum
        expr: sum(kubemq_messages_volume{type="events_store",side="receive"}) OR on() vector(0)
      - record: kubemq:messages:volume:events_store:sum
        expr: kubemq:messages:volume:events_store:send:sum+kubemq:messages:volume:events_store:receive:sum
      - record: kubemq:messages:errors:events_store:sum
        expr: sum(kubemq_errors_count{type="events_store"}) OR on() vector(0)
  - name: queues
    rules:
      - record: kubemq:messages:count:queues:send:sum
        expr: sum(kubemq_messages_count{type="queues",side="send"}) OR on() vector(0)
      - record: kubemq:messages:count:queues:receive:sum
        expr: sum(kubemq_messages_count{type="queues",side="receive"}) OR on() vector(0)
      - record: kubemq:messages:count:queues:sum
        expr: kubemq:messages:count:queues:send:sum+kubemq:messages:count:queues:receive:sum
      - record: kubemq:messages:volume:queues:send:sum
        expr: sum(kubemq_messages_volume{type="queues",side="send"}) OR on() vector(0)
      - record: kubemq:messages:volume:queues:receive:sum
        expr: sum(kubemq_messages_volume{type="queues",side="receive"}) OR on() vector(0)
      - record: kubemq:messages:volume:queues:sum
        expr: kubemq:messages:volume:queues:send:sum+kubemq:messages:volume:queues:receive:sum
      - record: kubemq:messages:errors:queues:sum
        expr: sum(kubemq_errors_count{type="queues"}) OR on() vector(0)
  - name: queries
    rules:
      - record: kubemq:messages:count:queries:send:sum
        expr: sum(kubemq_messages_count{type="queries",side="send"}) OR on() vector(0)
      - record: kubemq:messages:count:queries:receive:sum
        expr: sum(kubemq_messages_count{type="queries",side="receive"}) OR on() vector(0)
      - record: kubemq:messages:count:queries:sum
        expr: kubemq:messages:count:queries:send:sum+kubemq:messages:count:queries:receive:sum
      - record: kubemq:messages:volume:queries:send:sum
        expr: sum(kubemq_messages_volume{type="queries",side="send"}) OR on() vector(0)
      - record: kubemq:messages:volume:queries:receive:sum
        expr: sum(kubemq_messages_volume{type="queries",side="receive"}) OR on() vector(0)
      - record: kubemq:messages:volume:queries:sum
        expr: kubemq:messages:volume:queries:send:sum+kubemq:messages:volume:queries:receive:sum
      - record: kubemq:messages:errors:queries:sum
        expr: sum(kubemq_errors_count{type="queries"}) OR on() vector(0)
  - name: commands
    rules:
      - record: kubemq:messages:count:commands:send:sum
        expr: sum(kubemq_messages_count{type="commands",side="send"}) OR on() vector(0)
      - record: kubemq:messages:count:commands:receive:sum
        expr: sum(kubemq_messages_count{type="commands",side="receive"}) OR on() vector(0)
      - record: kubemq:messages:count:commands:sum
        expr: kubemq:messages:count:commands:send:sum+kubemq:messages:count:commands:receive:sum
      - record: kubemq:messages:volume:commands:send:sum
        expr: sum(kubemq_messages_volume{type="commands",side="send"}) OR on() vector(0)
      - record: kubemq:messages:volume:commands:receive:sum
        expr: sum(kubemq_messages_volume{type="commands",side="receive"}) OR on() vector(0)
      - record: kubemq:messages:volume:commands:sum
        expr: kubemq:messages:volume:commands:send:sum+kubemq:messages:volume:commands:receive:sum
      - record: kubemq:messages:errors:commands:sum
        expr: sum(kubemq_errors_count{type="commands"}) OR on() vector(0)
  - name: responses
    rules:
      - record: kubemq:messages:count:responses:sum
        expr: sum(kubemq_messages_count{type="responses"}) OR on() vector(0)
      - record: kubemq:messages:volume:responses:sum
        expr: sum(kubemq_messages_volume{type="responses"}) OR on() vector(0)
      - record: kubemq:messages:errors:responses:sum
        expr: sum(kubemq_errors_count{type="responses"}) OR on() vector(0)
