{
 "title": "Kubemq Dashboard",
 "description": "Kubemq Prometheus Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Overview Since inception", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Events Messages",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(kubemq_messages_count{type=\"events\",side=\"send\"}) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Total Events Store Messages",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "targets": [
    {
     "expr": "sum(kubemq_messages_count{type=\"events_store\",side=\"send\"}) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Total Queues Messages",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "sum(kubemq_messages_count{type=\"queues\",side=\"send\"})OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Total Queries Requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum(kubemq_messages_count{type=\"queries\",side=\"send\"}) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Total Commands Request",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "sum(kubemq_messages_count{type=\"commands\",side=\"send\"}) OR on() vector(0) "
    }
   ]
  },
  {
   "title": "Total Responses",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "targets": [
    {
     "expr": "sum(kubemq_messages_count{type=\"responses\"}) OR on() vector(0) "
    }
   ]
  },
  {
   "title": "Total Events Volume",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "sum(kubemq_messages_volume{type=\"events\"}) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Total Events Store Volume",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 5 },
   "targets": [
    {
     "expr": "sum(kubemq_messages_volume{type=\"events_store\"}) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Total Queues Messages Volume",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 5 },
   "targets": [
    {
     "expr": "sum(kubemq_messages_volume{type=\"queues\"})OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Total Queries Volume",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 5 },
   "targets": [
    {
     "expr": "sum(kubemq_messages_volume{type=\"queries\",side=\"send\"}) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Total Commands Volume",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 5 },
   "targets": [
    {
     "expr": "sum(kubemq_messages_volume{type=\"commands\",side=\"send\"}) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Total Response Volume",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 5 },
   "targets": [
    {
     "expr": "sum(kubemq_messages_volume{type=\"responses\"}) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Total Events Channels",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "count(sum by (channel)(kubemq_messages_count{type=\"events\"})) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Total Events Store Channels",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 9 },
   "targets": [
    {
     "expr": "count(sum by (channel)(kubemq_messages_count{type=\"events_store\"})) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Total Queues Channels",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 9 },
   "targets": [
    {
     "expr": "count(sum by (channel)(kubemq_messages_count{type=\"queues\"}))  OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Total Queries Channels",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "count(sum by (channel)(kubemq_messages_count{type=\"queries\"}))  OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Total Commands Channels",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 9 },
   "targets": [
    {
     "expr": "count(sum by (channel)(kubemq_messages_count{type=\"commands\"}))  OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Total Response Channels",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 9 },
   "targets": [
    {
     "expr": "count(sum by (channel)(kubemq_messages_count{type=\"responses\"}))  OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Total Events Clients",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "count(sum by (client_id)(kubemq_messages_count{type=\"events\"})) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Total Events Store Clients",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 13 },
   "targets": [
    {
     "expr": "count(sum by (client_id)(kubemq_messages_count{type=\"events_store\"})) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Total Queues Clients",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 13 },
   "targets": [
    {
     "expr": "count(sum by (client_id)(kubemq_messages_count{type=\"queues\"})) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Total Queries Clients",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "count(sum by (client_id)(kubemq_messages_count{type=\"queries\"})) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Total Commands Clients",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 13 },
   "targets": [
    {
     "expr": "count(sum by (client_id)(kubemq_messages_count{type=\"commands\"})) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Total Response Clients",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 13 },
   "targets": [
    {
     "expr": "count(sum by (client_id)(kubemq_messages_count{type=\"responses\"})) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Incoming Messages  Rate",
   "type": "graph",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short", "label": "Messages per second" }
   ],
   "targets": [
    {
     "expr": "sum by ()(rate(kubemq_messages_count{side=\"send\",type=\"events\"}[$__interval]) OR on() vector(0))",
     "legendFormat": "Events"
    },
    {
     "expr": "sum by ()(rate(kubemq_messages_count{side=\"send\",type=\"events_store\"}[$__interval]) OR on() vector(0))",
     "legendFormat": "Events Store"
    },
    {
     "expr": "sum by ()(rate(kubemq_messages_count{side=\"send\",type=\"queues\"}[$__interval]) OR on() vector(0))",
     "legendFormat": "Queues"
    },
    {
     "expr": "sum by ()(rate(kubemq_messages_count{side=\"send\",type=\"queries\"}[$__interval]) OR on() vector(0))",
     "legendFormat": "Queries"
    },
    {
     "expr": "sum by ()(rate(kubemq_messages_count{side=\"send\",type=\"commands\"}[$__interval]) OR on() vector(0))",
     "legendFormat": "Commands"
    }
   ]
  },
  {
   "title": "Incoming Volume Rate",
   "type": "graph",
   "gridPos": { "h": 11, "w": 6, "x": 6, "y": 17 },
   "yaxes": [
    { "format": "bps", "label": "Bits per second" }
   ],
   "targets": [
    {
     "expr": "sum by ()(rate(kubemq_messages_volume{side=\"send\",type=\"events\"}[$__interval])*8 OR on() vector(0))",
     "legendFormat": "Events"
    },
    {
     "expr": "sum by ()(rate(kubemq_messages_volume{side=\"send\",type=\"events_store\"}[$__interval]) *8 OR on() vector(0))",
     "legendFormat": "Events Store"
    },
    {
     "expr": "sum by ()(rate(kubemq_messages_volume{side=\"send\",type=\"queues\"}[$__interval]) * 8 OR on() vector(0))",
     "legendFormat": "Queues"
    },
    {
     "expr": "sum by ()(rate(kubemq_messages_volume{side=\"send\",type=\"queries\"}[$__interval]) *8 OR on() vector(0))",
     "legendFormat": "Queries"
    },
    {
     "expr": "sum by ()(rate(kubemq_messages_volume{side=\"send\",type=\"commands\"}[$__interval])*8 OR on() vector(0))",
     "legendFormat": "Commands"
    }
   ]
  },
  {
   "title": "Outgoing Messages  Rate",
   "type": "graph",
   "gridPos": { "h": 11, "w": 6, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short", "label": "Messages per second" }
   ],
   "targets": [
    {
     "expr": "sum by ()(rate(kubemq_messages_count{side=\"receive\",type=\"events\"}[$__interval]) OR on() vector(0))",
     "legendFormat": "Events"
    },
    {
     "expr": "sum by ()(rate(kubemq_messages_count{side=\"receive\",type=\"events_store\"}[$__interval]) OR on() vector(0))",
     "legendFormat": "Events Store"
    },
    {
     "expr": "sum by ()(rate(kubemq_messages_count{side=\"receive\",type=\"queues\"}[$__interval]) OR on() vector(0))",
     "legendFormat": "Queues"
    },
    {
     "expr": "sum by ()(rate(kubemq_messages_count{side=\"receive\",type=\"queries\"}[$__interval]) OR on() vector(0))",
     "legendFormat": "Queries"
    },
    {
     "expr": "sum by ()(rate(kubemq_messages_count{side=\"receive\",type=\"commands\"}[$__interval]) OR on() vector(0))",
     "legendFormat": "Commands"
    }
   ]
  },
  {
   "title": "Outgoing Volume Rate",
   "type": "graph",
   "gridPos": { "h": 11, "w": 6, "x": 18, "y": 17 },
   "yaxes": [
    { "format": "bps", "label": "Bytes per second" }
   ],
   "targets": [
    {
     "expr": "sum by ()(rate(kubemq_messages_volume{side=\"receive\",type=\"events\"}[$__interval]) * 8 OR on() vector(0))",
     "legendFormat": "Events"
    },
    {
     "expr": "sum by ()(rate(kubemq_messages_volume{side=\"receive\",type=\"events_store\"}[$__interval]) * 8 OR on() vector(0))",
     "legendFormat": "Events Store"
    },
    {
     "expr": "sum by ()(rate(kubemq_messages_volume{side=\"receive\",type=\"queues\"}[$__interval]) * 8 OR on() vector(0))",
     "legendFormat": "Queues"
    },
    {
     "expr": "sum by ()(rate(kubemq_messages_volume{side=\"receive\",type=\"queries\"}[$__interval]) * 8 OR on() vector(0))",
     "legendFormat": "Queries"
    },
    {
     "expr": "sum by ()(rate(kubemq_messages_volume{side=\"receive\",type=\"commands\"}[$__interval]) * 8 OR on() vector(0))",
     "legendFormat": "Commands"
    }
   ]
  },
  { "title": "Events", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Incoming Events Messages Rate",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 29 },
   "repeat": "messagetype",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by ()(rate(kubemq_messages_count{side=\"send\",type=\"events\"}[$__interval]) OR on() vector(0))"
    }
   ]
  },
  {
   "title": "Incoming Events Volume Rate",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 29 },
   "format": "bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by ()(rate(kubemq_messages_volume{side=\"send\",type=\"events\"}[$__interval])*8 OR on() vector(0))"
    }
   ]
  },
  {
   "title": "Outgoing Events Messages Rate",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 29 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by ()(rate(kubemq_messages_count{side=\"receive\",type=\"events\"}[$__interval]) OR on() vector(0))"
    }
   ]
  },
  {
   "title": "Incoming Events Volume Rate",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 29 },
   "format": "bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by ()(rate(kubemq_messages_volume{side=\"receive\",type=\"events\"}[$__interval]) * 8 OR on() vector(0))"
    }
   ]
  },
  {
   "title": "Clients",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "sum(kubemq_messages_count{type=\"events\"}) by(client_id,side) "
    },
    {
     "expr": "sum(kubemq_messages_volume{type=\"events\"}) by(client_id,side) "
    }
   ]
  },
  {
   "title": "Channels",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "expr": "sum(kubemq_messages_count{type=\"events\"}) by(channel,side) "
    },
    {
     "expr": "sum(kubemq_messages_volume{type=\"events\"}) by(channel,side) "
    }
   ]
  },
  { "title": "Events Store", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "Incoming Events Store Messages Rate",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 46 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by ()(rate(kubemq_messages_count{side=\"send\",type=\"events_store\"}[$__interval]) OR on() vector(0))"
    }
   ]
  },
  {
   "title": "Incoming Events Store Volume Rate",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 46 },
   "format": "bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by ()(rate(kubemq_messages_volume{side=\"send\",type=\"events_store\"}[$__interval]) * 8 OR on() vector(0))"
    }
   ]
  },
  {
   "title": "Outgoing Events Store Messages Rate",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 46 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by ()(rate(kubemq_messages_count{side=\"receive\",type=\"events_store\"}[$__interval]) OR on() vector(0))"
    }
   ]
  },
  {
   "title": "Incoming Events Store Volume Rate",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 46 },
   "format": "bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by ()(rate(kubemq_messages_volume{side=\"receive\",type=\"events_store\"}[$__interval]) * 8 OR on() vector(0))"
    }
   ]
  },
  {
   "title": "Clients",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 52 },
   "targets": [
    {
     "expr": "sum(kubemq_messages_count{type=\"events_store\"}) by(client_id,side) "
    },
    {
     "expr": "sum(kubemq_messages_volume{type=\"events_store\"}) by(client_id,side) "
    }
   ]
  },
  {
   "title": "Channels",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 52 },
   "targets": [
    {
     "expr": "sum(rate(kubemq_messages_count{type=\"events_store\"}[$__range])) by(channel,side) "
    },
    {
     "expr": "sum(rate(kubemq_messages_volume{type=\"events_store\"}[$__range])) by(channel,side) "
    }
   ]
  },
  { "title": "Queues", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 } },
  {
   "title": "Incoming Queues Messages Rate",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 63 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by ()(rate(kubemq_messages_count{side=\"send\",type=\"queues\"}[$__interval]) OR on() vector(0))"
    }
   ]
  },
  {
   "title": "Incoming Queues Volume Rate",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 63 },
   "format": "bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by ()(rate(kubemq_messages_volume{side=\"send\",type=\"queues\"}[$__interval]) * 8 OR on() vector(0))"
    }
   ]
  },
  {
   "title": "Outgoing Queues Messages Rate",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 63 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by ()(rate(kubemq_messages_count{side=\"receive\",type=\"queues\"}[$__interval]) OR on() vector(0))"
    }
   ]
  },
  {
   "title": "Outgoing Queues Volume Rate",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 63 },
   "format": "bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by ()(rate(kubemq_messages_volume{side=\"receive\",type=\"queues\"}[$__interval]) * 8 OR on() vector(0))"
    }
   ]
  },
  {
   "title": "Clients",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 69 },
   "targets": [
    {
     "expr": "sum(kubemq_messages_count{type=\"queues\"}) by(client_id,side) "
    },
    {
     "expr": "sum(kubemq_messages_volume{type=\"queues\"}) by(client_id,side) "
    }
   ]
  },
  {
   "title": "Channels",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 69 },
   "targets": [
    {
     "expr": "sum(kubemq_messages_count{type=\"queues\"}) by(channel,side) "
    },
    {
     "expr": "sum(kubemq_messages_volume{type=\"queues\"}) by(channel,side) "
    }
   ]
  },
  { "title": "Queries", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 79 } },
  {
   "title": "Incoming Queries Messages Rate",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 80 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by ()(rate(kubemq_messages_count{side=\"send\",type=\"queries\"}[$__interval]) OR on() vector(0))"
    }
   ]
  },
  {
   "title": "Incoming Queries Volume Rate",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 80 },
   "format": "bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by ()(rate(kubemq_messages_volume{side=\"send\",type=\"queries\"}[$__interval]) * 8 OR on() vector(0))"
    }
   ]
  },
  {
   "title": "Outgoing Queries Messages Rate",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 80 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by ()(rate(kubemq_messages_count{side=\"receive\",type=\"queries\"}[$__interval]) OR on() vector(0))"
    }
   ]
  },
  {
   "title": "Outgoing Queries Volume Rate",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 80 },
   "format": "bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by ()(rate(kubemq_messages_volume{side=\"receive\",type=\"queries\"}[$__interval]) * 8 OR on() vector(0))"
    }
   ]
  },
  {
   "title": "Clients",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 86 },
   "targets": [
    {
     "expr": "sum(kubemq_messages_count{type=\"queries\"}) by(client_id,side) "
    },
    {
     "expr": "sum(kubemq_messages_volume{type=\"queries\"}) by(client_id,side) "
    }
   ]
  },
  {
   "title": "Channels",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 86 },
   "targets": [
    {
     "expr": "sum(kubemq_messages_count{type=\"queries\"}) by(channel,side) "
    },
    {
     "expr": "sum(kubemq_messages_volume{type=\"queries\"}) by(channel,side) "
    }
   ]
  },
  { "title": "Commands", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 96 } },
  {
   "title": "Incoming Commands Messages Rate",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 97 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by ()(rate(kubemq_messages_count{side=\"send\",type=\"commands\"}[$__interval]) OR on() vector(0))"
    }
   ]
  },
  {
   "title": "Incoming Commands Volume Rate",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 97 },
   "format": "bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by ()(rate(kubemq_messages_volume{side=\"send\",type=\"commands\"}[$__interval]) * 8 OR on() vector(0))"
    }
   ]
  },
  {
   "title": "Outgoing Commands Messages Rate",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 97 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by ()(rate(kubemq_messages_count{side=\"receive\",type=\"commands\"}[$__interval]) OR on() vector(0))"
    }
   ]
  },
  {
   "title": "Outgoing Commands Volume Rate",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 97 },
   "format": "bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by ()(rate(kubemq_messages_volume{side=\"receive\",type=\"commands\"}[$__interval]) * 8 OR on() vector(0))"
    }
   ]
  },
  {
   "title": "Clients",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 103 },
   "targets": [
    {
     "expr": "sum(kubemq_messages_count{type=\"commands\"}) by(client_id,side) "
    },
    {
     "expr": "sum(kubemq_messages_volume{type=\"commands\"}) by(client_id,side) "
    }
   ]
  },
  {
   "title": "Channels",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 103 },
   "targets": [
    {
     "expr": "sum(kubemq_messages_count{type=\"commands\"}) by(channel,side) "
    },
    {
     "expr": "sum(kubemq_messages_volume{type=\"commands\"}) by(channel,side) "
    }
   ]
  }
 ]
}