{
  "apiVersion": 1,
  "datasources": [
  {
    "access":"proxy",
    "editable": false,
    "name": "prometheus",
    "isDefault": true,
    "orgId": 1,
    "type": "prometheus",
    "url": "http://localhost:9090",
    "version": 1
  }
  ]
}
